services:
  - type: web
    name: sgic-inventory-api
    env: node
    buildCommand: npm install --build-from-source
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
